MOSIP-26130 MOSIP-26131 MOSIP-26132 MOSIP-26133 MOSIPUpdated the IDP Test script with IDP linked api's and updated Readme …
mosip/mosip-performance-tests-mt pull request #102
Opened 2023-02-24 14:22 UTC by Sanjayss04

Updated the IDP test script with new IDP linked api's along with updation in readme file.

2023-03-23 12:50 UTC, vishwa-vyom requested changes

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/README.md
> +
"Value for both the fields must be verified in the env." - This line is confusing, what is expected from the user here ?

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/README.md
> +   * idp default properties: Update the value for the properties according to the execution setup. Perform the execution for IDP api's with redis setup. So check for the redis setup accordingly.
The file rename to esignet-default.properties in latest code, please change the file name and properties accordingly

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/README.md
> +
This should not be used for multiple executions, since transaction time has a expiry

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/README.md
> +
"Transaction id will be used which is created from the one started with link-transaction endpoint api" - Please rephrase since it confusing. I believe we should say link transaction id received from link-transaction endpoint api

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/README.md
> +
Change in other places of the readme also

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/README.md
> +   * Link Authorization Code (Execution) - Transaction id and linked code will pe used from the preparation part. Till the linked code is not expired the file can be used for multiple runs.
" will pe used" - Spell check

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/README.md
> +   * Link Authorization Code (Execution) - Transaction id and linked code will pe used from the preparation part. Till the linked code is not expired the file can be used for multiple runs.
Normally link code will have a short expiry like 5 min, so lets not tell that it can be resued

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/scripts/IDP_Test_Script.jmx
> +        <JSR223Sampler guiclass="TestBeanGUI" testclass="JSR223Sampler" testname="Generate Key Pair" enabled="true">
Once all the new thread groups are created,  including all the APIs, did we run all the preparation and exectution parallel to ensure all are able to run parallelly ?

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/scripts/IDP_Test_Script.jmx
> +          <stringProp name="script">import java.util.UUID;
For "Link Transaction Endpoint API" we don't need the CRSF token, if fact for all the below we don't need.
/v1/idp/linked-authorization/link-transaction
/v1/idp/linked-authorization/authenticate
/v1/idp/linked-authorization/consent

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/scripts/IDP_Test_Script.jmx
> +import java.util.Base64;
"UI - Linked Authentication (Preparation)" should be renamed to "UI - Linked Authentication - OTP (Preparation)" since we take care only the OTP flow. Later we need to add both biometric and wallet flow for the same. The default should be the wallet flow for the next consecutive API calls also. Can we create tasks for all these in the JIRA and link the same here ?

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/scripts/IDP_Test_Script.jmx
> +RSAKey jwk = new RSAKeyGenerator(2048)
Why we don't have performance test scripts for link-code and link-transaction endpoints ?

2023-03-23 12:50 UTC, vishwa-vyom commented on idp/scripts/IDP_Test_Script.jmx
> +    .generate();
UI - Link Authorization Code (Execution) -> Link Authorization Code Endpoint API -> oauth-hash - what is this header and why it is empty ?

2023-03-29 08:29 UTC, Sanjayss04 commented on idp/README.md
> +   * idp default properties: Update the value for the properties according to the execution setup. Perform the execution for IDP api's with redis setup. So check for the redis setup accordingly.
Done

2023-03-29 08:29 UTC, Sanjayss04 commented on idp/README.md
> +
Done

2023-03-29 08:29 UTC, Sanjayss04 commented on idp/README.md
> +
Done

2023-03-29 08:29 UTC, Sanjayss04 commented on idp/README.md
> +   * Link Authorization Code (Execution) - Transaction id and linked code will pe used from the preparation part. Till the linked code is not expired the file can be used for multiple runs.
Done

2023-03-29 08:37 UTC, Sanjayss04 commented on idp/README.md
> +   * Link Authorization Code (Execution) - Transaction id and linked code will pe used from the preparation part. Till the linked code is not expired the file can be used for multiple runs.
Done

2023-03-29 08:37 UTC, Sanjayss04 commented on idp/scripts/IDP_Test_Script.jmx
> +        <JSR223Sampler guiclass="TestBeanGUI" testclass="JSR223Sampler" testname="Generate Key Pair" enabled="true">
Yes, done.

2023-03-29 08:43 UTC, Sanjayss04 commented on idp/scripts/IDP_Test_Script.jmx
> +          <stringProp name="script">import java.util.UUID;
All Endpoint requires CSRF Token to be present in the Header. So have added to all the linked api's also.

2023-03-29 08:47 UTC, Sanjayss04 commented on idp/scripts/IDP_Test_Script.jmx
> +RSAKey jwk = new RSAKeyGenerator(2048)
Jira task were only created for the other linked api's so these two were not included. But, now have added test scripts for link-code and link-transaction endpoints.

2023-03-29 15:32 UTC, Sanjayss04 commented on idp/scripts/IDP_Test_Script.jmx
> +    .generate();
Taken Care

2023-03-29 15:32 UTC, Sanjayss04 commented on idp/scripts/IDP_Test_Script.jmx
> +import java.util.Base64;
Done.

For Jira task preparation will follow up with Hemant sir.

2023-03-30 11:55 UTC, Sanjayss04 commented on idp/README.md
> +
Updated

2023-05-02 12:39 UTC, vishwa-vyom commented on idp/scripts/IDP_Test_Script.jmx
> +          <stringProp name="script">import java.util.UUID;
Is the request failing if you remove it for the above mentioned API endpoints ?

2023-05-02 12:41 UTC, vishwa-vyom commented on idp/scripts/IDP_Test_Script.jmx
> +import java.util.Base64;
Can you add the links to Jira task here ?

2023-05-02 13:04 UTC, vishwa-vyom commented on idp/scripts/IDP_Test_Script.jmx
> +        <JSR223Sampler guiclass="TestBeanGUI" testclass="JSR223Sampler" testname="Generate Key Pair" enabled="true">
Did we find any issues while running this and it was fixed ?
For how many identities and how long we were running this in parallel ?

2023-05-03 07:28 UTC, Sanjayss04 commented on idp/scripts/IDP_Test_Script.jmx
> +        <JSR223Sampler guiclass="TestBeanGUI" testclass="JSR223Sampler" testname="Generate Key Pair" enabled="true">
No, we didn't find any issues while running the threads in parallel.
We have ran a small trial run for 5 users --- 5 mins.

<img width="576" alt="IDP" src="https://user-images.githubusercontent.com/107672790/235855152-c1745078-38a4-49ec-a538-fbb99c04021c.png">

2023-05-03 07:57 UTC, Sanjayss04 commented on idp/scripts/IDP_Test_Script.jmx
> +          <stringProp name="script">import java.util.UUID;
Yes, the request is failing if we remove the CSRF Token from the header. Have already cross checked.

2023-05-05 11:33 UTC, Sanjayss04 commented on idp/scripts/IDP_Test_Script.jmx
> +import java.util.Base64;
As discussed,
PFA link of the task below to which 2 tasks are created separately for biometric and wallet flow each linked to it.

https://mosip.atlassian.net/browse/MOSIP-26131

2023-05-05 12:42 UTC, vishwa-vyom approved these changes

2023-05-08 11:48 UTC, closed without merging