MOSIP-24463, MOSIP-24464, MOSIP-24465, MOSIP-24466   Updated the Mimoto scripts
mosip/mosip-performance-tests-mt pull request #105
Opened 2023-05-12 12:12 UTC by Sanjayss04

Updated the Mimoto Helper and Test script.

2023-05-24 14:31 UTC, vishwa-vyom requested changes

2023-05-24 14:31 UTC, vishwa-vyom commented on mimoto/scripts/Mimoto_Helper_Script.jmx
> +          </elementProp>
what is this variable, name is confusing

2023-05-24 14:31 UTC, vishwa-vyom commented on mimoto/scripts/Mimoto_Helper_Script.jmx
> +          <ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion" testname="Response Assertion - Response Code" enabled="true">
I see we are creating a token with resident app id and using in all the mimoto APIs, do we need this ?

2023-05-24 14:31 UTC, vishwa-vyom commented on mimoto/support-files/uinVidList.txt
> +2051478259,2406720417547968
This will should get autogenerated as part of setup, why should we commit this ?

2023-05-24 14:31 UTC, vishwa-vyom commented on mimoto/support-files/uinVidList.txt
> +2051478259,2406720417547968
this goes for other 2 txt files also

2023-05-24 14:31 UTC, vishwa-vyom commented on mimoto/scripts/Mimoto_Test_Script.jmx
> +      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Mimoto Request Credential API (Execution)" enabled="true">
Mimoto Request Credential API (Preparation) - Transaction ID Counter - CredentialRequest (UIN) - max value is same as others endpoints, will it not create issue when samples are high ?

2023-05-24 14:31 UTC, vishwa-vyom commented on mimoto/scripts/Mimoto_Test_Script.jmx
> +          <stringProp name="LoopController.loops">1</stringProp>
Mimoto Request Credential API (Preparation) - In thread group namings, i think we don't use the API at the back. Lets correct in all places

2023-05-24 14:31 UTC, vishwa-vyom commented on mimoto/scripts/Mimoto_Test_Script.jmx
> +        <stringProp name="ThreadGroup.ramp_time">1</stringProp>
where are we using the vid generated in the setup process ?

2023-05-24 14:31 UTC, vishwa-vyom commented on mimoto/scripts/Mimoto_Helper_Script.jmx
>            </elementProp>
In eSignet, I believe we moved the setup process to the same test script file, can we do the same for mimoto also ?

2023-05-24 14:31 UTC, vishwa-vyom commented on mimoto/scripts/Mimoto_Helper_Script.jmx
>            <stringProp name="HTTPSampler.protocol">${protocol}</stringProp>
Mimoto Req IndividualID OTP (Preparation) & Mimoto Aid Get-Individual-ID (Execution) are these related? naming is different here

2023-05-24 14:31 UTC, vishwa-vyom commented on mimoto/scripts/Mimoto_Helper_Script.jmx
> -            <stringProp name="Argument.value">abc123</stringProp>
Readme file to be added in the same format as eSignet

2023-05-26 08:26 UTC, Sanjayss04 commented on mimoto/scripts/Mimoto_Helper_Script.jmx
> +          </elementProp>
We have been using this variable name only where ever we are using the identity creation setup.

2023-05-26 08:59 UTC, Sanjayss04 commented on mimoto/support-files/uinVidList.txt
> +2051478259,2406720417547968
Okay @vishwa-vyom Removed both files.

2023-05-26 09:02 UTC, Sanjayss04 commented on mimoto/scripts/Mimoto_Helper_Script.jmx
>            </elementProp>
Moved the setup process to test script.

2023-05-26 09:08 UTC, Sanjayss04 commented on mimoto/scripts/Mimoto_Helper_Script.jmx
>            <stringProp name="HTTPSampler.protocol">${protocol}</stringProp>
Yes both are related, Mimoto Req IndividualID OTP api is required for the praparation so have added one more separate thread group for Mimoto Req IndividualID OTP (Execution).

2023-05-26 09:10 UTC, Sanjayss04 commented on mimoto/scripts/Mimoto_Test_Script.jmx
> +          <stringProp name="LoopController.loops">1</stringProp>
Updated

2023-05-26 09:29 UTC, Sanjayss04 commented on mimoto/scripts/Mimoto_Test_Script.jmx
> +      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Mimoto Request Credential API (Execution)" enabled="true">
I think we are using this same pattern everywhere, and the difference between all the Transaction ID Counter is 100M. I believe that should be fine.

2023-05-26 09:38 UTC, Sanjayss04 commented on mimoto/scripts/Mimoto_Test_Script.jmx
> +        <stringProp name="ThreadGroup.ramp_time">1</stringProp>
Currently we are not using the generated VID anywhere. Will remove it from the setup process.

2023-05-26 09:42 UTC, Sanjayss04 commented on mimoto/scripts/Mimoto_Helper_Script.jmx
> +          <ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion" testname="Response Assertion - Response Code" enabled="true">
The auth token generated with resident app id was used for authentication purpose and from starting we have added that in the header for all the api's. This thing I have to once check it by removing it. Will update once done.

2023-07-30 17:20 UTC, vishwa-vyom commented on mimoto/scripts/Mimoto_Helper_Script.jmx
> +          <ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion" testname="Response Assertion - Response Code" enabled="true">
Do we have the update on this ?

2023-07-30 17:29 UTC, vishwa-vyom approved these changes

2023-07-30 17:30 UTC, merged